<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ResidentSeeder extends Seeder
{
    public function run(): void
    {
        // User ID map:
        // 1 = admin
        // 2 = secretary1
        // 3–12 = clerk1–clerk10

        $residents = [
            // 1 — created by clerk1 (id:3)
            [
                'first_name'        => 'Jose',
                'middle_name'       => 'Reyes',
                'last_name'         => 'Delgado',
                'suffix'            => 'Jr.',
                'gender'            => 'Male',
                'birthdate'         => '1985-03-14',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Farmer',
                'mobile_number'     => '09171234501',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 9500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 18,
                'employment_status' => 'Self-Employed',
                'created_by'        => 3,
                'created_at'        => '2024-01-05 08:30:00',
                'updated_at'        => '2024-01-05 08:30:00',
            ],
            // 2 — created by clerk2 (id:4)
            [
                'first_name'        => 'Maria',
                'middle_name'       => 'Santos',
                'last_name'         => 'Flores',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1992-07-22',
                'place_of_birth'    => 'Davao City',
                'civil_status'      => 'Married',
                'occupation'        => 'Housewife',
                'mobile_number'     => '09181234502',
                'purok'             => 'Purok Mahigugmaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 0.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 10,
                'employment_status' => 'Unemployed',
                'created_by'        => 4,
                'created_at'        => '2024-01-10 09:15:00',
                'updated_at'        => '2024-01-10 09:15:00',
            ],
            // 3 — created by secretary (id:2)
            [
                'first_name'        => 'Roberto',
                'middle_name'       => null,
                'last_name'         => 'Ramos',
                'suffix'            => 'Sr.',
                'gender'            => 'Male',
                'birthdate'         => '1960-11-05',
                'place_of_birth'    => 'Compostela, Davao de Oro',
                'civil_status'      => 'Widowed',
                'occupation'        => 'Retired Farmer',
                'mobile_number'     => '09281234503',
                'purok'             => 'Purok Matinabangon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'Yes',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 5000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 35,
                'employment_status' => 'Retired',
                'created_by'        => 2,
                'created_at'        => '2024-01-15 10:00:00',
                'updated_at'        => '2024-01-15 10:00:00',
            ],
            // 4 — created by clerk3 (id:5)
            [
                'first_name'        => 'Ana',
                'middle_name'       => 'Cruz',
                'last_name'         => 'Villanueva',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1998-01-30',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Single',
                'occupation'        => 'Teacher',
                'mobile_number'     => '09991234504',
                'purok'             => 'Purok Malamposon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 25000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 27,
                'employment_status' => 'Employed',
                'created_by'        => 5,
                'created_at'        => '2024-01-20 11:45:00',
                'updated_at'        => '2024-01-20 11:45:00',
            ],
            // 5 — created by clerk4 (id:6)
            [
                'first_name'        => 'Eduardo',
                'middle_name'       => 'Bautista',
                'last_name'         => 'Mendoza',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1975-09-18',
                'place_of_birth'    => 'Maragusan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Tricycle Driver',
                'mobile_number'     => '09171234505',
                'purok'             => 'Purok Maasenso',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 11000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 22,
                'employment_status' => 'Self-Employed',
                'created_by'        => 6,
                'created_at'        => '2024-02-03 08:00:00',
                'updated_at'        => '2024-02-03 08:00:00',
            ],
            // 6 — created by clerk5 (id:7)
            [
                'first_name'        => 'Lourdes',
                'middle_name'       => null,
                'last_name'         => 'Garcia',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1989-04-09',
                'place_of_birth'    => 'Davao City',
                'civil_status'      => 'Separated',
                'occupation'        => 'Sari-sari Store Owner',
                'mobile_number'     => '09181234506',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 8000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 14,
                'employment_status' => 'Self-Employed',
                'created_by'        => 7,
                'created_at'        => '2024-02-10 13:20:00',
                'updated_at'        => '2024-02-10 13:20:00',
            ],
            // 7 — created by clerk6 (id:8)
            [
                'first_name'        => 'Rodel',
                'middle_name'       => 'Aquino',
                'last_name'         => 'Torres',
                'suffix'            => 'III',
                'gender'            => 'Male',
                'birthdate'         => '1970-06-25',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Barangay Tanod',
                'mobile_number'     => '09281234507',
                'purok'             => 'Purok Matinabangon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 7500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 40,
                'employment_status' => 'Employed',
                'created_by'        => 8,
                'created_at'        => '2024-02-18 09:30:00',
                'updated_at'        => '2024-02-18 09:30:00',
            ],
            // 8 — created by clerk7 (id:9)
            [
                'first_name'        => 'Cristina',
                'middle_name'       => 'Navarro',
                'last_name'         => 'Perez',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '2002-12-03',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Single',
                'occupation'        => 'Student',
                'mobile_number'     => '09991234508',
                'purok'             => 'Purok Mahigugmaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 0.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 22,
                'employment_status' => 'Student',
                'created_by'        => 9,
                'created_at'        => '2024-03-01 10:45:00',
                'updated_at'        => '2024-03-01 10:45:00',
            ],
            // 9 — created by clerk8 (id:10)
            [
                'first_name'        => 'Virgilio',
                'middle_name'       => null,
                'last_name'         => 'Hernandez',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1955-08-17',
                'place_of_birth'    => 'Maco, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Farmer',
                'mobile_number'     => '09171234509',
                'purok'             => 'Purok Mapagmahal',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'Yes',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 6000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 45,
                'employment_status' => 'Self-Employed',
                'created_by'        => 10,
                'created_at'        => '2024-03-08 14:00:00',
                'updated_at'        => '2024-03-08 14:00:00',
            ],
            // 10 — created by clerk9 (id:11)
            [
                'first_name'        => 'Sheryl',
                'middle_name'       => 'Lim',
                'last_name'         => 'Castillo',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1994-02-14',
                'place_of_birth'    => 'Tagum City',
                'civil_status'      => 'Married',
                'occupation'        => 'Nurse',
                'mobile_number'     => '09181234510',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 30000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 8,
                'employment_status' => 'Employed',
                'created_by'        => 11,
                'created_at'        => '2024-03-15 08:15:00',
                'updated_at'        => '2024-03-15 08:15:00',
            ],
            // 11 — created by clerk10 (id:12)
            [
                'first_name'        => 'Arnel',
                'middle_name'       => 'Dela Cruz',
                'last_name'         => 'Soriano',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1982-05-30',
                'place_of_birth'    => 'Compostela, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Carpenter',
                'mobile_number'     => '09281234511',
                'purok'             => 'Purok Matinabangon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 14000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 20,
                'employment_status' => 'Self-Employed',
                'created_by'        => 12,
                'created_at'        => '2024-03-22 11:00:00',
                'updated_at'        => '2024-03-22 11:00:00',
            ],
            // 12 — created by clerk1 (id:3)
            [
                'first_name'        => 'Nenita',
                'middle_name'       => 'Ybañez',
                'last_name'         => 'Reyes',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1967-10-11',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Widowed',
                'occupation'        => 'Vendor',
                'mobile_number'     => '09991234512',
                'purok'             => 'Purok Maasenso',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 7000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 30,
                'employment_status' => 'Self-Employed',
                'created_by'        => 3,
                'created_at'        => '2024-04-02 09:00:00',
                'updated_at'        => '2024-04-02 09:00:00',
            ],
            // 13 — created by clerk2 (id:4)
            [
                'first_name'        => 'Mark',
                'middle_name'       => null,
                'last_name'         => 'Buenaventura',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '2000-03-21',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Single',
                'occupation'        => 'Electrician',
                'mobile_number'     => '09171234513',
                'purok'             => 'Purok Mahigugmaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 16000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 25,
                'employment_status' => 'Employed',
                'created_by'        => 4,
                'created_at'        => '2024-04-10 13:30:00',
                'updated_at'        => '2024-04-10 13:30:00',
            ],
            // 14 — created by secretary (id:2)
            [
                'first_name'        => 'Felicitas',
                'middle_name'       => 'Ocampo',
                'last_name'         => 'Batungbakal',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1978-07-07',
                'place_of_birth'    => 'Nabunturan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Midwife',
                'mobile_number'     => '09181234514',
                'purok'             => 'Purok Mapagmahal',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 22000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 16,
                'employment_status' => 'Employed',
                'created_by'        => 2,
                'created_at'        => '2024-04-18 10:15:00',
                'updated_at'        => '2024-04-18 10:15:00',
            ],
            // 15 — created by clerk3 (id:5)
            [
                'first_name'        => 'Danilo',
                'middle_name'       => null,
                'last_name'         => 'Villafuerte',
                'suffix'            => 'Jr.',
                'gender'            => 'Male',
                'birthdate'         => '1990-01-15',
                'place_of_birth'    => 'Tagum City',
                'civil_status'      => 'Single',
                'occupation'        => 'Mechanic',
                'mobile_number'     => '09281234515',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 18000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 12,
                'employment_status' => 'Employed',
                'created_by'        => 5,
                'created_at'        => '2024-05-05 08:45:00',
                'updated_at'        => '2024-05-05 08:45:00',
            ],
            // 16 — created by clerk4 (id:6)
            [
                'first_name'        => 'Rosario',
                'middle_name'       => 'Ferrer',
                'last_name'         => 'Dela Torre',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1963-12-28',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Farmer',
                'mobile_number'     => '09991234516',
                'purok'             => 'Purok Matinabangon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 9000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 42,
                'employment_status' => 'Self-Employed',
                'created_by'        => 6,
                'created_at'        => '2024-05-12 14:20:00',
                'updated_at'        => '2024-05-12 14:20:00',
            ],
            // 17 — created by clerk5 (id:7)
            [
                'first_name'        => 'Jomar',
                'middle_name'       => 'Tan',
                'last_name'         => 'Evangelista',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1995-08-04',
                'place_of_birth'    => 'Davao City',
                'civil_status'      => 'Single',
                'occupation'        => 'Security Guard',
                'mobile_number'     => '09171234517',
                'purok'             => 'Purok Malamposon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 13000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 6,
                'employment_status' => 'Employed',
                'created_by'        => 7,
                'created_at'        => '2024-05-20 09:10:00',
                'updated_at'        => '2024-05-20 09:10:00',
            ],
            // 18 — created by clerk6 (id:8)
            [
                'first_name'        => 'Ligaya',
                'middle_name'       => null,
                'last_name'         => 'Magbanua',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1985-06-19',
                'place_of_birth'    => 'Maco, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Dressmaker',
                'mobile_number'     => '09181234518',
                'purok'             => 'Purok Maasenso',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 10500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 15,
                'employment_status' => 'Self-Employed',
                'created_by'        => 8,
                'created_at'        => '2024-06-03 11:30:00',
                'updated_at'        => '2024-06-03 11:30:00',
            ],
            // 19 — created by clerk7 (id:9)
            [
                'first_name'        => 'Fernando',
                'middle_name'       => 'Oreta',
                'last_name'         => 'Padilla',
                'suffix'            => 'Sr.',
                'gender'            => 'Male',
                'birthdate'         => '1958-04-23',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Retired',
                'mobile_number'     => '09281234519',
                'purok'             => 'Purok Mahigugmaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'Yes',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 5500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 50,
                'employment_status' => 'Retired',
                'created_by'        => 9,
                'created_at'        => '2024-06-11 08:00:00',
                'updated_at'        => '2024-06-11 08:00:00',
            ],
            // 20 — created by clerk8 (id:10)
            [
                'first_name'        => 'Hazel',
                'middle_name'       => 'Salonga',
                'last_name'         => 'Mercado',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '2003-09-12',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Single',
                'occupation'        => 'Student',
                'mobile_number'     => '09991234520',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'No',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 0.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 21,
                'employment_status' => 'Student',
                'created_by'        => 10,
                'created_at'        => '2024-06-20 15:00:00',
                'updated_at'        => '2024-06-20 15:00:00',
            ],
            // 21 — created by clerk9 (id:11)
            [
                'first_name'        => 'Romulo',
                'middle_name'       => null,
                'last_name'         => 'Alcantara',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1973-02-08',
                'place_of_birth'    => 'Compostela, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Fisherman',
                'mobile_number'     => '09171234521',
                'purok'             => 'Purok Matinabangon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 8500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 28,
                'employment_status' => 'Self-Employed',
                'created_by'        => 11,
                'created_at'        => '2024-07-04 10:30:00',
                'updated_at'        => '2024-07-04 10:30:00',
            ],
            // 22 — created by clerk10 (id:12)
            [
                'first_name'        => 'Glenda',
                'middle_name'       => 'Ilagan',
                'last_name'         => 'Quiambao',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1980-11-25',
                'place_of_birth'    => 'Tagum City',
                'civil_status'      => 'Married',
                'occupation'        => 'Teacher',
                'mobile_number'     => '09181234522',
                'purok'             => 'Purok Mapagmahal',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 26000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 19,
                'employment_status' => 'Employed',
                'created_by'        => 12,
                'created_at'        => '2024-07-12 09:45:00',
                'updated_at'        => '2024-07-12 09:45:00',
            ],
            // 23 — created by clerk1 (id:3)
            [
                'first_name'        => 'Benjamin',
                'middle_name'       => 'Pascual',
                'last_name'         => 'Umali',
                'suffix'            => 'Jr.',
                'gender'            => 'Male',
                'birthdate'         => '1987-05-16',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Welder',
                'mobile_number'     => '09281234523',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 17000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 38,
                'employment_status' => 'Employed',
                'created_by'        => 3,
                'created_at'        => '2024-07-22 13:00:00',
                'updated_at'        => '2024-07-22 13:00:00',
            ],
            // 24 — created by clerk2 (id:4)
            [
                'first_name'        => 'Teresita',
                'middle_name'       => null,
                'last_name'         => 'Bonifacio',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1970-03-01',
                'place_of_birth'    => 'Maco, Davao de Oro',
                'civil_status'      => 'Widowed',
                'occupation'        => 'Laundrywoman',
                'mobile_number'     => '09991234524',
                'purok'             => 'Purok Maasenso',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 6500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 32,
                'employment_status' => 'Self-Employed',
                'created_by'        => 4,
                'created_at'        => '2024-08-05 08:20:00',
                'updated_at'        => '2024-08-05 08:20:00',
            ],
            // 25 — created by secretary (id:2)
            [
                'first_name'        => 'Julius',
                'middle_name'       => 'Guinto',
                'last_name'         => 'Espiritu',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1997-10-20',
                'place_of_birth'    => 'Davao City',
                'civil_status'      => 'Single',
                'occupation'        => 'Delivery Rider',
                'mobile_number'     => '09171234525',
                'purok'             => 'Purok Mahigugmaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 15000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 5,
                'employment_status' => 'Employed',
                'created_by'        => 2,
                'created_at'        => '2024-08-14 11:15:00',
                'updated_at'        => '2024-08-14 11:15:00',
            ],
            // 26 — created by clerk3 (id:5)
            [
                'first_name'        => 'Mildred',
                'middle_name'       => 'Ponce',
                'last_name'         => 'Domingo',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1993-01-06',
                'place_of_birth'    => 'Nabunturan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Bookkeeper',
                'mobile_number'     => '09181234526',
                'purok'             => 'Purok Malamposon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 20000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 9,
                'employment_status' => 'Employed',
                'created_by'        => 5,
                'created_at'        => '2024-08-22 14:45:00',
                'updated_at'        => '2024-08-22 14:45:00',
            ],
            // 27 — created by clerk4 (id:6)
            [
                'first_name'        => 'Ernesto',
                'middle_name'       => null,
                'last_name'         => 'Macalintal',
                'suffix'            => 'Sr.',
                'gender'            => 'Male',
                'birthdate'         => '1952-07-31',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Retired Barangay Official',
                'mobile_number'     => '09281234527',
                'purok'             => 'Purok Matinabangon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'Yes',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 4500.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 55,
                'employment_status' => 'Retired',
                'created_by'        => 6,
                'created_at'        => '2024-09-03 09:00:00',
                'updated_at'        => '2024-09-03 09:00:00',
            ],
            // 28 — created by clerk5 (id:7)
            [
                'first_name'        => 'Charity',
                'middle_name'       => 'Manalo',
                'last_name'         => 'Aguilar',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '2001-04-17',
                'place_of_birth'    => 'Pantukan, Davao de Oro',
                'civil_status'      => 'Single',
                'occupation'        => 'Call Center Agent',
                'mobile_number'     => '09991234528',
                'purok'             => 'Purok Mahigalaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 19000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 24,
                'employment_status' => 'Employed',
                'created_by'        => 7,
                'created_at'        => '2024-09-10 10:30:00',
                'updated_at'        => '2024-09-10 10:30:00',
            ],
            // 29 — created by clerk6 (id:8)
            [
                'first_name'        => 'Conrado',
                'middle_name'       => 'Valdez',
                'last_name'         => 'Macaraeg',
                'suffix'            => null,
                'gender'            => 'Male',
                'birthdate'         => '1965-09-09',
                'place_of_birth'    => 'Compostela, Davao de Oro',
                'civil_status'      => 'Married',
                'occupation'        => 'Gold Miner',
                'mobile_number'     => '09171234529',
                'purok'             => 'Purok Maasenso',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'No',
                'resident_status'   => 'Active',
                'monthly_income'    => 12000.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 36,
                'employment_status' => 'Self-Employed',
                'created_by'        => 8,
                'created_at'        => '2024-09-18 13:45:00',
                'updated_at'        => '2024-09-18 13:45:00',
            ],
            // 30 — created by clerk7 (id:9)
            [
                'first_name'        => 'Maricel',
                'middle_name'       => null,
                'last_name'         => 'Bacalso',
                'suffix'            => null,
                'gender'            => 'Female',
                'birthdate'         => '1988-12-01',
                'place_of_birth'    => 'Tagum City',
                'civil_status'      => 'Separated',
                'occupation'        => 'Market Vendor',
                'mobile_number'     => '09181234530',
                'purok'             => 'Purok Mahigugmaon',
                'barangay'          => 'Kingking',
                'municipality'      => 'Pantukan',
                'province'          => 'Davao de Oro',
                'voter_status'      => 'Yes',
                'pwd_status'        => 'No',
                'fourps_status'     => 'Yes',
                'resident_status'   => 'Active',
                'monthly_income'    => 9800.00,
                'citizenship'       => 'Filipino',
                'years_of_residency'=> 13,
                'employment_status' => 'Self-Employed',
                'created_by'        => 9,
                'created_at'        => '2024-09-25 08:00:00',
                'updated_at'        => '2024-09-25 08:00:00',
            ],
        ];

        foreach ($residents as $resident) {
            DB::table('residents')->insert($resident);
        }
    }
}